### ISSUE TITLE
Tweet needs to be a bit shorter

### ISSUE THREAD

**Issue by truekasun** [adblanc/twit-thread#13]
I'm using twit-thread module on one of my services and normally it splits the message to a safe limit and posts as a thread (when using ```tweetThread``` method).

But I noticed that it does not work fine when I post the following text. The text contains **447 characters**.

```YouTube mobile app වල videos download කරගැනීමේ පහසුකම තිබුණත් මේ දක්වා එම පහසුකම YouTube web app එකේ දකින්නට ලැබුණේ නැහැ.\n\nකොහොම වුණත් මේ වන විට එම පහසුකම Web app එකට එකතු කිරීමට YouTube ආයතනය කටයුතු කර තිබෙනවා.\n\nyoutube.com/new වෙබ් අඩවිය හරහා මෙම පහසුකම මේ වන විටත් YouTube Premium පරිශීලකයින් හට, සීමාසහිත කාලයකට අත්හදාබැලීමේ හැකියාව ලබාදීමට ඔවුන් කටයුතු කර තිබෙනවා.\n\nවැඩි විස්තර සඳහා 👇\nhttps://s.techie.lk/dUsz\n\n#TechNewsLK #Instants```

When I try to post this with the tweetThread method, I get the following error.

**Message:** ```Tweet needs to be a bit shorter.```
**Stack Trace:**
``` 
Error: Tweet needs to be a bit shorter.
    at Object.exports.makeTwitError (d:\Codeaffinity\Image\node_modules\twit\lib\helpers.js:74:13)
    at onRequestComplete (d:\Codeaffinity\Image\node_modules\twit\lib\twitter.js:344:25)
    at Request.<anonymous> (d:\Codeaffinity\Image\node_modules\twit\lib\twitter.js:364:7)
    at Request.emit (events.js:387:35)
    at Gunzip.<anonymous> (d:\Codeaffinity\Image\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:481:28)
    at Gunzip.emit (events.js:375:28)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)```

---

Node: v14.17.3
twit-thread: 2.1.0
OS: Windows 10/Ubuntu 18.04

**Comment by truekasun** [comment]
When I remove the URL in the body (youtube.com/new), it posted without any issue.

**Comment by webbrain-one** [comment]
Hi! 👋

Thanks for the detailed report. I've opened [PR #20](https://github.com/adblanc/twit-thread/pull/20) to address this issue.

The fix corrects the character length calculation logic, ensuring the text is split properly without exceeding Twitter's limit. This should resolve the "Tweet needs to be a bit shorter" error you're encountering.

Please let me know if you have any other questions! 🚀
